version: '3'

services:
  web:
    restart: always
    image: roadini_api
    command: bash -c "sleep 15 && python roadini/manage.py makemigrations && python roadini/manage.py migrate && python roadini/manage.py runserver 0.0.0.0:8000"
    container_name: roadini_api
    volumes:
        - .:/roadiniApi
    ports:
        - "8000:8000"
    depends_on:
        - postgres
    networks: 
        - proxynet
  
          # nginx:
          # restart: always
          # image: nginx:1.13
          # ports:
          # - "80:80"
          # volumes:
          # - ./config/nginx/conf.d:/etc/nginx/conf.d
          # - ./config/nginx/nginx.conf:/etc/nginx/nginx.conf
          # depends_on:
          # - web
          # expose:
          # - "80"
          # networks:
          # - proxynet

  postgres:
    container_name: roadini_db
    restart: always
    image: launcher.gcr.io/google/postgresql10
    volumes:
        - ./postgres/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
        - ./backups/postgresql:/backupo
    environment:
        - POSTGRES_USER=admin
        - POSTGRES_PASSWORD=admin
        - POSTGRES_DB=roadinidb
    networks:
        - proxynet

networks: 
    proxynet: 
        driver: bridge
