# Generated by Django 2.1.2 on 2018-10-23 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PathsTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('socialID', models.IntegerField()),
                ('pathID', models.IntegerField()),
            ],
        ),
    ]
