# Generated by Django 2.1.3 on 2018-11-25 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appAPI', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ListPostPhoto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('listId', models.IntegerField()),
                ('postId', models.IntegerField()),
                ('imageId', models.TextField()),
            ],
        ),
    ]
