# Generated by Django 2.1.3 on 2018-11-25 23:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appAPI', '0002_listpostphoto'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='listpostphoto',
            unique_together={('listId', 'postId', 'imageId')},
        ),
        migrations.AlterModelTable(
            name='listpostphoto',
            table='ListPostPhoto',
        ),
    ]
