# Generated by Django 2.1.3 on 2018-11-27 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appAPI', '0003_auto_20181125_2356'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAuth',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userId', models.IntegerField()),
                ('cookie', models.TextField()),
            ],
            options={
                'db_table': 'UserAuth',
            },
        ),
        migrations.AlterUniqueTogether(
            name='userauth',
            unique_together={('userId',)},
        ),
    ]
